// Bu dosya tanimlar.pdf dosyasindan otomatik uretilmistir.
export const TANIMLAR = {
    TEHLIKE_KAYNAKLARI: [
    "3. Kişi Yada Kurumların Etkisi",
    "Acil Durum Alarm Sistemi Eksiklikleri",
    "Acil Durumlara Hazırlıklı Olmama",
    "Acil Durumlarda Geç Müdahale",
    "Ankraj Ve Kurulum Kusurları",
    "Arıtma Tesisi Yetersizliği",
    "Arıtma Tesisine Aşırı Sıvı Yükleme",
    "Asbestli malzeme kullanımı",
    "Atık Gönderiminde Olumsuzluk",
    "Atık Kutusu Eksikliği",
    "Atık Oluşumu",
    "Atık Yönetimi Uygunsuzluğu",
    "Atıkların Ayrıştırılmaması",
    "Aşındırıcı Kimyasallar",
    "Aşırı Yük Taşıma",
    "Bacalar",
    "Basınç Altındaki Gazlar",
    "Basınçlı Kaplar",
    "Bağışıklama Eksikliği",
    "Başıboş Hayvan Varlığı ve Haşeratlar",
    "Bilgi Eksikliği",
    "Bilinçsiz Müdahale",
    "Biyolojik Arıtma Bakterilerinin Ölmesi",
    "Biyolojik atıklara temas",
    "Boğucu-Zehirleyici Gaz Varlığı",
    "Büyük Hacimli Yük Taşıma",
    "Dalgınlık",
    "Dağınık İş Ortamı",
    "Deformasyon, Korozyon Bulunması",
    "Dengesiz Yük Taşıma",
    "Depolama Matrisi Harici Uygulama",
    "Deporte-Tutuklu Yolcu",
    "Deprem Bölgesinde Bulunma",
    "Dere Yatağında Bulunma",
    "Dezenfeksiyon Eksikliği",
    "Değişim Yönetimi Zaafiyeti",
    "Dikkatsizlik",
    "Doğal Afetler (Deprem, Sel, Fırtına vb)",
    "Doğal Gaz Kaçağı",
    "Döner Aksam",
    "Düzensiz Çalışma",
    "Düşme Tehditli Cisim",
    "Düşme önleyici sistem eksikliği",
    "Ehil Olmayan Personel",
    "Ekipman - Araç Eksikliği",
    "Elektrik",
    "Emisyon",
    "Ergonomik Olmayan Ekipman",
    "Ergonomik olmayan çalışma koşulları",
    "Ergonomik olmayan çalışma koşulları( Alçak tavan, kapalı ve dar mekanlar)",
    "Etiketleme Eksikliği",
    "Eğitim Eksikliği",
    "Fazla Mesai",
    "Fazla İş Yükü",
    "Gece Çalışma",
    "Görev Tanımı Harici Faaliyet",
    "Görev tanımı belirsizliği",
    "Görev tanımının yapılmamış olması",
    "Görüş Alanı-Açısı Yetersizliği",
    "Gözlem",
    "Güvenlik Tertibatı-Önlemi Eksikliği",
    "Hasarlı Kaplar",
    "Hasarlı Yapı-Bina",
    "Hasarlı/Arızalı/Uygunsuz İş Ekipmanı Kullanımı",
    "Hasta Yolcu",
    "Hatalı Nakliye İşlemleri",
    "Hayvan Isırması",
    "Hayvan Saldırısı",
    "Hayvan Tırmalaması",
    "Haşere Isırması/Sokması",
    "Haşere Varlığı",
    "Hijyen Eksikliği",
    "INAD Yolcu",
    "Kaygan-ıslak zemin",
    "Keskin sivri yüzeyler",
    "Keyif verici madde kullanımı (Alkol, uyuşturucu vs)",
    "Kimyasal Dökülmeler",
    "Kimyasal Kullanımı",
    "Kimyasal Sızıntı",
    "Kişisel Hijyen Eksikliği",
    "Kişisel Koruyucu Donanım Eksikliği",
    "Kişisel koruyucu donanım kullanmama",
    "Kişiye Uygun Olmayan KKD",
    "Kot farkı",
    "Kural Dışı Davranış",
    "Kural Dışı Yolcu",
    "Kısıtlı Alan Olması",
    "Majör",
    "Makine talimatının olmamas-Talimat eksikliği",
    "Medical Kesici - Delici Aletler",
    "Mental Zayıflık",
    "Meslek hastalığı teşhisinin yapılamaması",
    "Minör",
    "Mobbing-Taciz",
    "Monotonluk",
    "Msds Bulunmaması",
    "Oksitleyici Gazlar",
    "Organizasyon-Koordinasyon Yetersizliği",
    "Oryantasyon Eksikliği",
    "Parlayıcı Patlayıcı Varlığı",
    "Periyodik Bakım ve Onarım Eksikliği",
    "Periyodik Kontrol Eksikliği",
    "Periyodik Kontrol-Kalibrasyon Eksikliği",
    "Pestisitler",
    "Radyasyon",
    "Riskli Alanlara Kontrolsüz Giriş-Çıkış",
    "Riskli Alanlara Kontrolsüz Giriş-çıkış",
    "Sabitlenmemiş Ekipman",
    "Sabotaj ve Saldırı Tehlikesi",
    "Salgın Tehditli Alanda Bulunma-çalışma",
    "Sağlık Ve Güvenlik İşaretlerinin Eksikliği",
    "Sefer Gecikmesi",
    "Silahlı Yolcu (Güvenlik Vb)",
    "Sokak Hayvanı Varlığı",
    "Soğuk Yüzey",
    "Standart Olmayan Malzeme Kullanımı",
    "Standart eksikliği",
    "Statik Elektrik",
    "Sıcak İşler",
    "Talimat Eksikliği",
    "Tanımsız Kap Kullanımı",
    "Tarihi Geçmiş Gıdalar",
    "Tarihi Geçmiş İlaçlar",
    "Tatbikat eksikliği",
    "Taşma Kabı Kapasitesinin Yetersiz Olması",
    "Tecrübe Eksikliği",
    "Tekrarlanan fiziksel hareketler",
    "Toksik Kimyasallar",
    "Toplanma ve Gösteri Merkezlerine Yakın Bulunma",
    "Uygun Olmayan Depolama Koşulları",
    "Uygun Olmayan Ekipman-Araç",
    "Uygun Olmayan Saklama Koşulları",
    "Uygun Olmayan Termal Koşullar(Sıcak-Soğuk)",
    "Uygun Olmayan Yapı-Bina Ve Eklentiler",
    "Uygun Olmayan Yerleşim/Konum( makine, malzeme, tesis vb.)",
    "Uygun Olmayan Yöntem",
    "Uygun Olmayan Çevresel Koşullar(Gürültü, Aydınlatma, Toz Vb.)",
    "Uygun Olmayan İstif-Depolama",
    "Uygun olmayan konfigirasyon",
    "Uygunsuzluk Bulunmamaktadır",
    "Uykusuzluk",
    "Uzun Süreli Çalışma",
    "Vardiyalı Çalışma",
    "Vücut Sıvıları İle Temas",
    "Yalnız Çalışma",
    "Yangın",
    "Yanıcı Malzeme Varlığı",
    "Yasal Mevzuat Uygunluk Takibinin olmaması",
    "Yağ Yakıt Dökülmesi",
    "Yetersiz Atık Sahası",
    "Yetersiz Dinlenme",
    "Yetersiz Oksijen",
    "Yetkisiz Müdahale",
    "Yolcu-Personel İlişkileri",
    "Yorgunluk",
    "Yoğun araç trafiği",
    "Yönetsel Ve Disiplin Eksikliği",
    "Yüksekte Çalışma",
    "Yürüme Yolu - Araç Yolu Eksiklikleri",
    "Zaman Baskısı",
    "Zemin Bozukluğu(şekilsiz, stabil olmayan zemin)",
    "Zorlayıcı Meteorolojik Koşullu Bölge",
    "ortak kullanılan giysi, araç ve gereçler",
    "Çalışanın Fiziksel Yetersizliği",
    "Ücret Beklentisinin Karşılanamaması",
    "İklim Değişikliği",
    "İklimlendirme-Havalandırma Eksikliği",
    "İlaç Etkisinde Çalışma",
    "İletişim Eksikliği",
    "İsg Etki Analizi Yapılmaması",
    "İstem Dışı/Ani Hareket",
    "İyileştirmeye Açık Alan",
    "İş Güvencesinin Olmaması",
    "İş hijyeni ölçümlerinin yapılmaması",
    "İş İzni Olmaması",
    "İşe Uygun Olmayan KKD",
    "Şakalaşma"
],
    RISKLER: [
    "Alerjik Etkiler",
    "Araç Çarpması/Trafik kazası",
    "Arızalı, hasarlı ekipman kullanımı",
    "Asbestli malzeme kullanımı",
    "Barotravma",
    "Batma",
    "Biyolojik Bulaşma-Yayılım",
    "Boğucu-Zehirli Gaz Maruziyeti",
    "Boğulma(suda-dumanda)",
    "Bulaşıcı Hastalıklara Maruziyet",
    "Böcek Sokması",
    "Cam kesmesi",
    "Ceza",
    "Cisim Düşmesi",
    "Devrilme",
    "Dolaşım Sistemi Rahatsızlıkları",
    "Duman Maruziyeti",
    "Duran Bir Cisme Çarpma",
    "Elektrik Maruziyeti",
    "Elektrik Tesisatına Aşırı Yükleme",
    "Elektromanyetik Alan Maruziyeti",
    "Enerji Sarfiyatı",
    "Ezilme",
    "Fiziksel Şiddet",
    "Gasp",
    "Göze yabancı cisim kaçması",
    "Gözlerin Aşırı Yorulması",
    "Gürültü Maruziyeti",
    "Gıda Zehirlenmesi",
    "Hareketli Bir Cismin Çarpması",
    "Hastalık",
    "Hatalı Tıbbi Müdahale",
    "Hava Akımına Maruziyet",
    "Hava Kirliliği",
    "Hayvan Tarafından Isırılma",
    "Hipoksi",
    "Kargaşa - İzdiham",
    "Kargaşa-İzdiham",
    "Kas-İskelet Sistemi Zorlanması",
    "Kayma/Takılma/Düşme",
    "Kesik",
    "Kimyasal Buharına Maruziyet",
    "Kimyasal Madde Yangınları",
    "Kimyasal Madde Yutulması",
    "Kimyasal Maddeye Temas",
    "Kirli hava maruziyeti",
    "Kontrolsüz enerjiye maruz kalma(Hava, Elektrik,Su)",
    "Kozmik Radyasyon Maruziyeti",
    "Kütle düşmesi",
    "Maddi Hasarlı Kaza",
    "Maddi Kayıp",
    "Meslek Hastalığı",
    "Meslek hastalığına teşhisinin yapılamaması",
    "Muhtelif Hastalık Riski",
    "Müdahalede Gecikme",
    "Parça Sıçraması",
    "Patlama-Parlama",
    "Periyodik muayene veya kalibrasyon eksikliği",
    "Postür Bozuklukları",
    "Psikomotor Fonksiyonlarda Azalma",
    "Radyoaktif maruziyet",
    "Sağlığın Bozulması",
    "Sindirim Sistemi Rahatsızlıkları",
    "Soğuk Maruziyeti",
    "Stres",
    "Su Kirliliği",
    "Sıcak Maruziyeti",
    "Sıkışma",
    "Tahliyede Gecikme",
    "Tanımlanmamış- öngörülemeyen riskler",
    "Termal Yanık",
    "Terör ve diğer saldırı türleri",
    "Titreşim Maruziyeti",
    "Toplu Ölüm",
    "Toprak Kirliliği",
    "Toz Maruziyeti",
    "Tıbbi Radyasyon Maruziyeti",
    "Uzuv Kaybı",
    "Uçak Kazası",
    "Yangın",
    "Yaralanma",
    "Yasal Uyumsuzluk",
    "Yağma",
    "Yetersiz beslenme",
    "Yönetimsel Riskler",
    "Yük Devrilmesi",
    "Yüksekten Düşme",
    "Yıkıntı, göçük altında kalma",
    "iş günü kayıplı hastalık",
    "Çevre Kirliliği",
    "Çevre İzin Belgesi Alınamaması",
    "Çeşitli Psikolojik Etkiler",
    "Ölüm",
    "İlaç Zehirlenmesi",
    "İş Gücü Kaybı",
    "İş Günü Kayıplı Kaza",
    "İşi eğitimsiz çalışanın yapması"
],
    MEVZUATLAR: [
    "4857 İş Kanunu",
    "5510 Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu",
    "6331 İş Sağlığı ve Güvenliği Kanunu",
    "Alt İşverenlik Yönetmeliği",
    "Asansör Periyodik Kontrol Yönetmeliği",
    "Asansör Yönetmeliği",
    "Asansör İşletme ve Bakım Yönetmeliği",
    "Basit Basınçlı Kaplar Yönetmeliği",
    "Binaların Yangından Korunması Hakkında Yönetmelik",
    "Biyolojik Etkenlere Maruziyet Risklerinin Önlenmesi Hakkında Yönetmelik",
    "Büyük Endüstriyel Kazaların Önlenmesi ve Etkilerinin Azaltılması HakkındaYönetmelik",
    "CCM",
    "Ekranlı Araçlarla Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "Elektrik Tesisatçıları Hakkında Yönetmelik",
    "Elektrik Tesislerinde Topraklamalar Yönetmeliği",
    "Elektrik İle İlgili Fen Adamlarının Yetki, Görev ve Sorumlulukları Hakkında Yönetmelik",
    "Elektrik İç Tesisleri Yönetmeliği",
    "Elle Taşıma İşleri Yönetmeliği",
    "Gebe veya Emziren Kadınların Çalıştırılma Şartlarıyla Emzirme Odaları ve Çocuk Bakım Yurtlarına Dair Yönetmelik",
    "Geçici veya Belirli Süreli İşlerde İSG Hakkında Yönetmelik",
    "Havacılık Sağlık Talimatı (SHT-MED)",
    "Hijyen Eğitimi Yönetmeliği",
    "IATA Medical Manuel",
    "ICAO Annex 1 Chapter 6. Medical Provisions for Licensing",
    "Kadın Çalışanların Gece Postalarında Çalıştırılma Koşulları Hakkında Yönetmelik",
    "Kanserojen ve Mutajen Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "Karayolları Trafik Yönetmeliği",
    "Kimyasal Maddelerle Çalışmalarda Sağlık ve Güvenlik Önlemleri Hakkında Yönetmelik",
    "Kişisel Koruyucu Donanım Yönetmeliği",
    "Kişisel Koruyucu Donanımlarla İlgili Uyumlaştırılmış Ulusal Standartlara Dair Tebliğ",
    "Kişisel Koruyucu Donanımların İşyerlerinde Kullanılması Hakkında Yönetmelik",
    "Kontrole Tabi Havacılık Personelinin Alkol ve Psikoaktif Madde Kontrollerine İlişkin Talimat (SHT-APAM)",
    "Maddelerin ve Karışımların Sınıflandırılması, Etiketlenmesi ve Ambalajlanması Hakkında Yönetmelik",
    "Postalar Halinde İşçi Çalıştırılarak Yürütülen İş. Çalışmalara İlişkin Özel Usul ve Esas Hak. Yönetmelik",
    "Radyasyon Acil Durumlarının Yönetimine Dair Yönetmelik",
    "Radyasyon Güvenliği Yönetmeliği",
    "Radyoaktif Maddenin Güvenli Taşınması Yönetmeliği",
    "SHT-FTL Uçuş ve Görev Süresi Sınırlamaları İle Dinlenme Gereklilikleri Talimatı",
    "SHT-FTL/HG Hava Taksi ve Genel Havacılık İşletmeleri İçin Uçuş Görev Süresi Sınırlamaları İle Dinlenme Gereklilikleri Talimatı",
    "Sağlık Kuralları Bakımından Günde Azami Yedi Buçuk Saat Veya Daha Az Çalışılması Gereken İşler Hakkında Yönetmelik",
    "Sağlık ve Güvenlik İşaretleri Yönetmeliği",
    "Taşınabilir Basınçlı Ekipmanlar Yönetmeliği",
    "Tehlikeli ve Çok Tehlikeli Sınıfta Yer Alan İşlerde Çalıştırılacakların Mesleki Eğitimlerine Dair Yönetmelik",
    "Toplu İş Sözleşmesi",
    "Tozla Mücadele Yönetmeliği",
    "Tozla Mücadele ile İlgili Uygulamalara İlişkin Tebliğ",
    "TÜTÜN ÜRÜNLERİNİN ZARARLARININ ÖNLENMESİ VE KONTROLÜ HAKKINDA KANUN",
    "Tıbbi Atıkların Kontrolü Yönetmeliği",
    "UOD-2020/3G Uçuş Operasyonları Esnasında Covid-19 Tedbirleri Hakkında Genelge",
    "UOD-2020/4 COVID-19- Havacılık Personeli Sağlık Muayeneleri Konulu Genelge",
    "Uzaktan Çalışma Yönetmeliği",
    "Yapı İşlerinde İSG Yönetmeliği",
    "Yurtiçinde İşe Yerleştirme Hizmetleri Hakkında Yönetmelik",
    "Çalışanların Gürültü ile İlgili Risklerden Korunmalarına Dair Yönetmelik",
    "Çalışanların Patlayıcı Ortamların Tehlikelerinden Korunması Hakkında Yönetmelik",
    "Çalışanların Titreşimle ilgili Risklerden Korunmalarına Dair Yönetmelik",
    "Çalışanların İş Sağlığı ve Güvenliği Eğitimlerinin Usul ve Esasları Hakkında Yönetmelik",
    "İSG Uzmanlarının Görev, Yetki, Sorumluluk ve Eğitimleri Hakkında Yönetmelik",
    "İSG ile İlgili Çalışan Temsilcisinin Nitelikleri ve Seçilme Usul ve Esaslarına İlişkin Tebliğ",
    "İlkyardım Yönetmeliği",
    "İnsani Tüketim Amaçlı Sular Hakkında Yönetmelik",
    "İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmelik",
    "İş Hijyeni Ölçüm, Test ve Analiz Laboratuvarları Hakkında Yönetmelik",
    "İş Kanununa İlişkin Fazla Çalışma ve Fazla Sürelerle Çalışma Yönetmelik",
    "İş Kanununa İlişkin Çalışma Süreleri Yönetmeliği",
    "İş Sağlığı ve Güvenliği Hizmetleri Yönetmeliği",
    "İş Sağlığı ve Güvenliği Hizmetlerinin Desteklenmesi Hakkında Tebliğ",
    "İş Sağlığı ve Güvenliği Hizmetlerinin Desteklenmesi Hakkında Yönetmelik",
    "İş Sağlığı ve Güvenliği Kurulları Hakkında Yönetmelik",
    "İş Sağlığı ve Güvenliği Risk Değerlendirmesi Yönetmeliği",
    "İş Sağlığı ve Güvenliğine İlişkin Tehlike Sınıfları Tebliği",
    "İşkolları Yönetmeliği",
    "İşyeri Bina ve Eklentilerinde Alınacak Sağlık ve Güvenlik Önlemlerine İlişkin Yönetmelik",
    "İşyeri Hekimi ve Diğer Sağlık Personelinin Görev, Yetki, Sorumluluk ve Eğitimleri Hakkında Yönetmelik",
    "İşyerlerinde Acil Durumlar Hakkında Yönetmelik",
    "İşyerlerinde İşin Durdurulmasına Dair Yönetmelik",
    "İşyerlerinde İşveren veya İşveren Vekili tarafından Yürütülecek İSG Hizmetlerine İlişkin Yönetmelik"
]
};
